---
deployment:
  tasks:
    - export DEPLOYPATH=/home/khw2ft6zoaa3/public_html/nanayasa.ph
    - /bin/mkdir -p $DEPLOYPATH/storage/framework/cache
    - /bin/mkdir -p $DEPLOYPATH/storage/framework/sessions
    - /bin/mkdir -p $DEPLOYPATH/storage/framework/views
    - /bin/mkdir -p $DEPLOYPATH/storage/logs
    - /bin/mkdir -p $DEPLOYPATH/bootstrap/cache
    - /bin/chmod -R 755 $DEPLOYPATH/storage
    - /bin/chmod -R 755 $DEPLOYPATH/bootstrap/cache
    - /bin/cp -R public/build $DEPLOYPATH/public
    - /bin/cp public/.htaccess $DEPLOYPATH/public/.htaccess
